version: '3.3'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"  # Porta do PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./core/db_scripts:/docker-entrypoint-initdb.d  # Monta o diretório local de scripts no container

  flask:
    build:
      context: ./core/admin_panel  # Caminho do código do painel Flask
      args:
        FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
        DATABASE_URL: ${DATABASE_URL}
    container_name: flask_app
    ports:
      - "5020:5000"  # Porta do Flask
    depends_on:
      - postgres
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: ${DATABASE_URL}  # Conexão com o PostgreSQL usando variável do .env
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}

volumes:
  postgres_data:
